### ISSUE TITLE
How to build for iOS?

### ISSUE THREAD

**Issue by janpio** [sthewissen/KickassUI.Spotify#1]
I know nothing about Xamarin. 

How can I build this as an iOS app?

(Asking because I might want to help here: https://github.com/fastlane/fastlane/issues/9857)

**Comment by sthewissen** [comment]
This isn't really an issue with this project so I'm closing it. The only thing I can tell you is to start learning Xamarin. This is not the place for that. There are a lot of tutorials on their website on how to build your first app that are worth reading through to get an idea on how to get started.
