### ISSUE TITLE
Question Re: Iconography

### ISSUE THREAD

**Issue by shainefisher** [sthewissen/KickassUI.Spotify#2]
Where are the icons from, and more importantly, where can I get others? Please.

This is excellent by the way, on my Android device the command for the play button doesn't work, but I really don't care. The layout technique is excellent, and there are so many well executed sections of code in this project.

Thanks :)

**Comment by sthewissen** [comment]
Hey Shaine, thanks for the kind words! The Android play button thing might be true. Main focus of this tutorial was creating the actual layout, not making a fully functional app. The icons are basically taken from the original app by taking screenshots and cutting them out.

**Comment by shainefisher** [comment]
That seems like a lot of work, I think I'll just try and find some, or break out Illustrator.
Yeah, I was just looking at the layout technique you used, I like the way you've executed this, and the Twitter client.
Thanks for sharing :)
